apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshop-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ThibautHI/tp_docker_avance_6.git
    targetRevision: develop
    path: k8s/statefulsets
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshop-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
