apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshop-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ThibautHI/tp_docker_avance_6.git
    targetRevision: develop
    path: k8s
    directory:
      include: "{namespaces,configs}/**/*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshop-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
